### ISSUE TITLE
Yotpo Configuration in Single Store mode

### ISSUE THREAD

**Issue by hobadams** [YotpoLtd/magento2-module-yotpo-reviews#164] opened 2019-06-27 10:05 UTC
Hey guys,

I'm using 2.8.1 of your module.

I've noticed that some of the store configs don't appear in the admin if you are running on single store mode.

I believe this is because of `showInDefault="0"`. The configs save but isn't visible on store view 0 (in the admin)

![Screenshot 2019-06-27 at 11 04 07](https://user-images.githubusercontent.com/9551929/60257432-59917a00-98cb-11e9-8b8e-cad2338d38d4.png)
<img width="483" alt="Screenshot 2019-06-27 at 11 03 55" src="https://user-images.githubusercontent.com/9551929/60257433-59917a00-98cb-11e9-82f3-4c2deae0966f.png">

So far the fields I can see that this impacts are enabled, app key and app secret.

Thanks

**Comment by SlavicB** [comment] 2019-06-30 08:52
Hey @hobadams ,

Those fields disabled by design, Yotpo is configured in a store scope, there is no global scope config.
Even with a single store the configuration is done in that store's scope.

**Comment by hobadams** [comment] 2019-07-01 08:35
Thanks @SlavicB. 

For us the means we can't see the config settings as there is no way to view that store in the admin.

**Comment by SlavicB** [comment] 2019-07-02 11:06
Even with a single store you should have a store view, can you please provide a screenshot of the whole page.
That's how the page looks in the two different states:
![Screen Shot 2019-07-02 at 14 04 53](https://user-images.githubusercontent.com/20300814/60508175-90ec9600-9cd2-11e9-8f97-aa4b1fd07d4c.png)
![Screen Shot 2019-07-02 at 14 04 20](https://user-images.githubusercontent.com/20300814/60508180-93e78680-9cd2-11e9-91b0-f12618e59a8c.png)

**Comment by hobadams** [comment] 2019-07-02 13:52
<img width="531" alt="Screenshot 2019-07-02 at 14 50 38" src="https://user-images.githubusercontent.com/9551929/60518126-cc8a5e80-9cd8-11e9-9e5a-7700f8bcb7ab.png">
<img width="1117" alt="Screenshot 2019-07-02 at 14 50 16" src="https://user-images.githubusercontent.com/9551929/60518127-cd22f500-9cd8-11e9-8e84-30d8ad0bac5d.png">

Hey @SlavicB these are screen grabs from my admin.

This store is Magento 2.2.3 EE.

It only has 1 store so you don't get the store drop down.

Thanks

**Comment by Sazoulay** [comment] 2019-07-08 16:54
Hi @hobadams 

Even in a single store view mode, you should be able to get all the relevant settings.  
<img width="960" alt="2019-07-09_00h51_24" src="https://user-images.githubusercontent.com/44259724/60827937-fac8dc00-a1b9-11e9-9ff1-13d1965b30a2.png">

Could you please elaborate on what options you are missing? 
Or please send screenshots that contain all the Yotpo plugin settings as the screenshot provided only provides a partial view. 

Thank you.

**Comment by SlavicB** [comment] 2019-07-16 10:34
That's an issue with EE from what I see, we will address this in one of our upcoming releases, thank you for reporting this.

**Comment by hobadams** [comment] 2019-07-24 13:22
Thank you.

Are you ok to drop me an email when this is resolved.

Thanks
Hob Adams
Senior Developer
[image: Gene Commerce - specialist ecommerce agency]
<http://gene.co.uk/> [image:
Magento Solutions Partner] [image: Magento 2 Solutions Partner]
<https://magento.com/>
T: +44(0) 1273 030390 | 20 Middle Street, Brighton, BN1 1AL
[image: Twitter Logo] <https://twitter.com/gene_commerce> [image: LinkedIn
Logo] <https://www.linkedin.com/company/gene-commerce>
gene.co.uk
Registered Office: 20 Middle Street, Brighton, BN1 1AL. Registered in
England and Wales No.08589522

**Comment by DanGlz** [comment] 2019-11-14 09:48
Hey @hobadams,

This bug has been fixed in the latest release (v2.9.2).

Let us know if there is any issue.
Thanks.

**Closed** 2020-02-18 16:32 UTC
Labels: bug
